import{i as n,S as d}from"./assets/vendor-8c59ed88.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const f="43963855-b23ab28bc2f72f8207f09d24a",y="https://pixabay.com/api/",h=o=>{const s=new URLSearchParams({key:`${f}`,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`${y}?${s}`).then(r=>{if(!r.ok)throw new Error(r.statusText);return r.json()})};function g(o){return o.map(({webformatURL:s,largeImageURL:r,tags:a,likes:e,views:t,comments:l,downloads:u})=>`<li class="gallery-item">
            <a class="gallery-link" href="${r}">
              <img class="gallery-img" src="${s}" alt="${a}" />
            </a>
            <div class="small-info">
             <small class="text-body-likes">Likes: ${e}</small>
             <small class="text-body-views">Views: ${t}</small>
             <small class="text-body-comments">Comments: ${l}</small>
             <small class="text-body-downloads">Downloads: ${u}</small>
            </div>
          </li>`).join("")}const p=document.querySelector(".search-form"),c=document.querySelector(".gallery-list"),m=document.querySelector(".loader");let i;function b(o){o.preventDefault();const s=o.target.querySelector(".form-input").value.trim();if(c.innerHTML="",s===""){o.target.reset(),n.show({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}m.classList.remove("is-hidden"),h(s).then(r=>{if(r.hits.length===0)n.show({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});else{const a=g(r.hits);c.insertAdjacentHTML("beforeend",a),i?i.refresh():i=new d(".gallery-list a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250,className:"my-custom-lightbox"})}}).catch(r=>console.log(r)).finally(()=>{o.target.reset(),m.classList.add("is-hidden")})}p.addEventListener("submit",b);
//# sourceMappingURL=commonHelpers.js.map
